### PR TITLE
VueJS fixes for v1.0.26

### PR DESCRIPTION
**Pull request by Piterden**
### VueJS

| **Version used** | **1.0.26** |
| --- | --- |
| Language used | ES6 |
| **Templating logic** | **Vue** |
| Text interpolation | `{{ message }}` |
| Transform interpolation | `{{ message | filter }}` |
| Transform with arguments | `{{ message | filter 'arg1' arg2 }}` |
| Bind text content | `<div v-text="message">` |
| "Bind dangerous html content by directive" | `<div v-html="message">` |
| Bind href | `<a v-bind:href="url"></a> or <a v-link="url"></a>` Official vue-router plugin is the best way, I think. But we can use shorthand syntax like `<a :href="url"></a>` Anyway, both methods are not recommended. |
| Dangerous raw HTML output | `{{{ raw_html }}}` |
| Bind attribute value | `<div id="item-{{ id }}">` |
| DOM add/remove | `<div v-if='shouldShow'>` and `<div v-else='shouldShow'>` |
| DOM show/hide | `<div v-show='shouldShow'>` and `<div v-else='shouldShow'>` |
| Repeat | `<div v-for="(index, item) in items"></div>` or `<div v-for="(key, val) in object"></div>` |
| Bind event handler | `<button v-on:click="clicked">` or just `<button @click="clicked">` |
| Preventing and stopping events | `<form @submit.stop.prevent="submit">` |
| Bink keypresses | `<input @keyup.enter="save">` |
| **Components** | **Vue** |
| Define component ES6 | `class Polyglot extends Vue` |
|  | Also you can define collections of components directly in property «components» of vue instance, using ES6 syntax components: {Copm1,Comp2,Comp3} |
| Define component ES5 | `Vue.extend({}) or Vue.component(name, {})" |
| **Component communication** | **Vue** |
| One-way data binding | `<child :foo='bar' />` |
| String literal prop | `<child foo='bar' />` |
| Two-way binding (native) | `<input v-model="foo" />` |
| Two-way binding (components) | `<child :foo.sync="bar"></child>` |
| One-time binding | `<child :foo.once="bar" />` |
| **Component internal state** | **Vue** |
| Set initial state | `data: { foo: 1 }` |
| If you need to set nested data values you have to use function returning value | `data: { return { model: {}, collection: [] }}` |
| Set state | `this.foo = 2` |
| **Property validation** | **Vue** |
| Prop validation key | `{props: {}}` |
| Required props without type set | `{email: { required: true }}` |
| Prop validate Number | `{myNum: Number}` |
| Prop validate String | `{myStr: String}` |
| Prop validate Array | `{myArr: Array}` |
| Prop validate Boolean | `{myBool: Boolean}` |
| Prop validate Function | `{myFunc: Function}` (Now supported by vue) |
| Prop validate Object | `{myObj: Object}` |
| Prop validate Date | `{myDate: Date}` It`s not documented, but I have some experience with this feature and don`t have any errors |
| Prop validate union | `{myVar: [String, Number]}` |
| **Component lifecycle methods** | **Vue** |
| Initialized | `init` `created` |
| Before compile template | `beforeCompile` |
| After compile template | `compiled` |
| DOM Ready | `ready` |
| On prop change | no |
| Component updated | no |
| Before destroy | `beforeDestroy` |
| After destroy | `destroyed` |

### CODE REVIEW

**Comment by jeffcarp** [comment]
Thanks for converting your changes into text, are there any of your own changes in this PR?

**Comment by Piterden** [comment]
All changes in this PR (this table) is my own.
But if you mean changes directly to VueJS then no, it's not me))

9 июля 2016 г. 12:21 AM пользователь "Jeff Carpenter" <
notifications@github.com> написал:

**Comment by jeffcarp** [comment]
The changes for this PR are currently contained in the PR comment. If they're converted to actual changes, I can merge them. Otherwise, at some point if I have the time I can make the code changes.

**Comment by jeffcarp** [comment]
Closing. I don't have time to convert this PR into a usable format.

**Pull request closed without merging**
